### ISSUE TITLE
You forgot to copy-paste the Go copyright and license

### ISSUE THREAD

**Issue by Yawning** [coinbase/kryptology#13]
I'm sure this is a honest mistake, but why does this library contain files derived from the Go standard library with a different copyright and license?

https://github.com/coinbase/kryptology/blob/3d28fe04e750bc4f1f321174a4a79f9e8f378d40/pkg/ted25519/ted25519/ed25519.go 
https://github.com/golang/go/blob/54e75e8f9db09868db61f97edb98ace3aab7234f/src/crypto/ed25519/ed25519.go

I get that the backend curve/scalar implementation was replaced (by the same code that the standard library later switched to), but it still is a derived work.

**Comment by Arash-Afshar** [comment]
Thanks for pointing it out @Yawning. It appears it was dropped during some code movement and the new copyright header was added by an automated tool. We'll address this in the next release.

**Comment by mikelodder7** [comment]
Fixed in #24

**Comment by Yawning** [comment]
Yay.
