### ISSUE TITLE
"cap out of range error" in pkg/signatures/bbs/pok_signature_proof.go

### ISSUE THREAD

**Issue by boumba100** [coinbase/kryptology#31]
### Expected Behaviour

Calling [GetContributionChallenge](https://github.com/coinbase/kryptology/blob/58aa4ba5ff28eb3a202700a272a4384940760c22/pkg/signatures/bbs/pok_signature_proof.go#L114) for all revealed proof messages should not throw an error.

### Actual Behaviour

The function throws the following error:\
`panic: runtime error: makeslice: cap out of range`

### Steps to Reproduce the Problem

In the test file, replace [proofMsgs](https://github.com/coinbase/kryptology/blob/58aa4ba5ff28eb3a202700a272a4384940760c22/pkg/signatures/bbs/pok_signature_proof_test.go#L43) with the following

```go
	proofMsgs := []common.ProofMessage{
		&common.RevealedMessage{
			Message: msgs[0],
		},
		&common.RevealedMessage{
			Message: msgs[1],
		},
		&common.RevealedMessage{
			Message: msgs[2],
		},
		&common.RevealedMessage{
			Message: msgs[3],
		},
	}
```

and replace the [revealedMsgs](https://github.com/coinbase/kryptology/blob/58aa4ba5ff28eb3a202700a272a4384940760c22/pkg/signatures/bbs/pok_signature_proof_test.go#L74) with

```go
	revealedMsgs := map[int]curves.Scalar{
		0: msgs[0],
		1: msgs[1],
		2: msgs[2],
		3: msgs[3],
	}
```

### Issue

The following [expression](https://github.com/coinbase/kryptology/blob/58aa4ba5ff28eb3a202700a272a4384940760c22/pkg/signatures/bbs/pok_signature_proof.go#L142) calculates an expected array capacity that is smaller than the length of [proof2Points](https://github.com/coinbase/kryptology/blob/58aa4ba5ff28eb3a202700a272a4384940760c22/pkg/signatures/bbs/pok_signature_proof.go#L143) and [proof2Scalars](https://github.com/coinbase/kryptology/blob/58aa4ba5ff28eb3a202700a272a4384940760c22/pkg/signatures/bbs/pok_signature_proof.go#L144).

### Suggested Fix

Replace `pts := 2 + generators.length - len(revealedMessages)` with `	pts := 3 + generators.length - len(revealedMessages)`

Replace `2` with `3` since the affected arrays have a minimum length of 3.

**Comment by mikelodder7** [comment]
Good catch.  Looks like you already submitted a PR. Will review.
