### ISSUE TITLE
Using the `camshoup` verifiable encryption package

### ISSUE THREAD

**Issue by Olshansk** [coinbase/kryptology#40]
I recently looked into using the `camshoup` package to be used in a VRFworkflow, but have a few questions:

1. Is it possible to rename `DecryptionKey` and `EncryptionKey` to `VerificationKey` and `SecretKey` respectively?

2. Image 1 below shows that the `EncryptionKey` can be retrieved from the `DecryptionKey`. I looked through some of the reference papers (image 3) and additional documentation (image 2), but still don't fully understand how this should be used.

    If a verifier, who has access to the `DecryptionKey`, can retrieve the `EncryptionKey`, then anyone can recreate the proof. My expectation is that the `DecryptionKey` (i.e. the Public Key) can be used for verification, the `EncryptionKey` (i.e. the Secret Key) can be used for encryption, and `DecryptionKey` can be derived from the `EncryptionKey`.

    If my understanding here is incorrect, then the first question is a moot point.

3. What is the purpose of the `numMsgs` parameter when calling [NewKeys](https://github.com/coinbase/kryptology/blob/master/pkg/verenc/camshoup/encryption_key.go#L34)? It seems that it controls the number of messages that the [ciphertext could contain](https://github.com/coinbase/kryptology/blob/master/pkg/verenc/camshoup/decryption_key.go#L93) but is this a design decision or a technical limitation? In other words, why not simply use the same key and treat each ciphertext as a separate message (i.e. numMessages is always exactly 1).

## Image 1:  README in this [github repo](https://github.com/coinbase/kryptology/blob/dc0a42bc61ec533aa1d3257c7d8b094cfcfbb4f4/pkg/verenc/camshoup/README.md):
<img width="1113" alt="Screen Shot 2022-02-01 at 11 37 53 PM" src="https://user-images.githubusercontent.com/1892194/152093975-2146b8c6-900f-4678-b6a3-047a6d98749b.png">

## Image 2: README in this [github repo](https://github.com/coinbase/kryptology/blob/dc0a42bc61ec533aa1d3257c7d8b094cfcfbb4f4/pkg/verenc/camshoup/README.md):
<img width="657" alt="Screen Shot 2022-02-01 at 11 31 14 PM" src="https://user-images.githubusercontent.com/1892194/152093512-cbf3c3a2-5030-4ce5-be9e-ba622c4e41a4.png">

## Image 3:  The referenced paper [Practical Verifiable Encryption and Decryption of Discrete Logarithms](https://shoup.net/papers/verenc.pdf):
<img width="545" alt="Screen Shot 2022-02-01 at 11 34 25 PM" src="https://user-images.githubusercontent.com/1892194/152093833-d8e730a5-c537-4325-aae0-9c08fee739b1.png">

**Comment by mikelodder7** [comment]
> I recently looked into using the `camshoup` package to be used in a VRFworkflow, but have a few questions:
> 
> 1. Is it possible to rename `DecryptionKey` and `EncryptionKey` to `VerificationKey` and `SecretKey` respectively?
No these are really encryption and decryption keys, not just proving and verifying.

> 2. Image 1 below shows that the `EncryptionKey` can be retrieved from the `DecryptionKey`. I looked through some of the reference papers (image 3) and additional documentation (image 2), but still don't fully understand how this should be used.
>    If a verifier, who has access to the `DecryptionKey`, can retrieve the `EncryptionKey`, then anyone can recreate the proof. My expectation is that the `DecryptionKey` (i.e. the Public Key) can be used for verification, the `EncryptionKey` (i.e. the Secret Key) can be used for encryption, and `DecryptionKey` can be derived from the `EncryptionKey`.

The verifier shouldn't have access to the decryption key. The prover is showing they encrypted a message(s) to the encryption key. The verifier can check that the statement is true.

>    If my understanding here is incorrect, then the first question is a moot point.
> 3. What is the purpose of the `numMsgs` parameter when calling [NewKeys](https://github.com/coinbase/kryptology/blob/master/pkg/verenc/camshoup/encryption_key.go#L34)? It seems that it controls the number of messages that the [ciphertext could contain](https://github.com/coinbase/kryptology/blob/master/pkg/verenc/camshoup/decryption_key.go#L93) but is this a design decision or a technical limitation? In other words, why not simply use the same key and treat each ciphertext as a separate message (i.e. numMessages is always exactly 1).

This stems from the paper that you can have multiple messages in a single proof vs creating N proofs. Efficiency and succinctness are two reasons for this approach. It's not a technical limitation.

**Comment by mikelodder7** [comment]
Addressed

**Comment by Olshansk** [comment]
@mikelodder7 Per the naming convention, that you can retrieve the `EncryptionKey` given the `DecryptionKey` in the function I highlighted above?

Doesn't this give the verifier the ability to encrypt as well?

**Comment by Olshansk** [comment]
@massitaverna I'm slightly confused as well.
