### ISSUE TITLE
Issue in SecretKeyShare.UnmarshalBinary

### ISSUE THREAD

**Issue by dB2510** [coinbase/kryptology#51]
I am suspecting there is a bug in https://github.com/coinbase/kryptology/blob/f7f15f217682f3e13b88846a419bce94bc3f7f73/pkg/signatures/bls/bls_sig/lib.go#L144 When calling UnmarshalBinary on bls_sig.SecretKeyShare struct it gives empty value attribute. 
Here's the way to reproduce it: https://github.com/coinbase/kryptology/pull/50
Here's the possible fix to this issue: https://github.com/coinbase/kryptology/pull/52

We at Obol when updated to latest v1.8.0 found this issue while updating our codebase.

**Comment by dB2510** [comment]
@mikelodder7

**Comment by mikelodder7** [comment]
Odd because our tests are passing. I’ll take a look on monday

**Comment by dB2510** [comment]
> Odd because our tests are passing. I’ll take a look on monday

Sure, thanks

**Comment by Arash-Afshar** [comment]
Interesting that the new test you submitted also does not seem to catch it : https://github.com/coinbase/kryptology/pull/50 I'll try to reproduce
